
#/images
  description: Endpoint for images upload
  post:
    description: Upload new image
    responses:
      200:
        body:
          example: '{"imageUrl": "http://www.lorempixel.com/100/200"}'
